/**
 * make-money-cartoon-short
 *
 * Local economy-cartoon Shorts pipeline:
 *   ComfyUI text-to-image keyposes -> local MeloTTS -> boltYT Remotion Shorts.
 *
 * This deliberately avoids stock footage and PIL-drawn fake animation. The visual
 * assets are generated by the local ComfyUI stack, then edited with the existing
 * production Remotion composition.
 */
import { execFile } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { remotionMotionFor } from "../src/lib/camera-movements.ts";
import { renderVlogRemotion } from "./remotion-vlog-render.ts";
import { dur, runComfyChecked, textToImageWorkflow } from "./vlog-shared.ts";

const exec = promisify(execFile);
const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_OUT = join(PROJECT_ROOT, "output", "money-cartoon");
const MELO_TTS =
	process.env.MELO_TTS ?? "/Users/jjuni/AI/video-factory/bin/tts-melo.sh";

interface SceneSpec {
	id: string;
	narration: string;
	visual: string;
	cameraMove:
		| "slow-zoom-in"
		| "slider-right"
		| "whip-pan-right"
		| "crash-zoom-in"
		| "handheld";
}

const SCENES: SceneSpec[] = [
	{
		id: "payday-hook",
		narration:
			"월급날 통장 숫자는 분명 늘어났는데, 이상하게 마음은 하나도 안 편하죠.",
		visual:
			"vertical 9:16 flat Korean economy cartoon, recurring simple office worker character staring at a smartphone bank app, a cheerful green paycheck mascot enters the screen, clean vector illustration, bold outlines, warm editorial colors, original character design, no text, no letters, no watermark",
		cameraMove: "slow-zoom-in",
	},
	{
		id: "fixed-costs-chase",
		narration:
			"그 이유는 월세, 식비, 구독료 같은 고정비가 월급보다 먼저 달려오기 때문입니다.",
		visual:
			"same Korean office worker character running across a simple apartment floor while cute monster bills for rent, food, subscriptions chase a green paycheck mascot, slapstick economy cartoon, flat vector style, clear action pose, no text, no letters",
		cameraMove: "slider-right",
	},
	{
		id: "inflation-balloon",
		narration:
			"물가가 오르면 월급은 그대로인데, 장바구니와 커피값은 풍선처럼 커집니다.",
		visual:
			"same character holding a tiny shopping basket under a huge red inflation balloon lifting price tags and coffee cups, visual metaphor for inflation, expressive cartoon explainer, flat 2D vector, bold clean outlines, no text, no letters",
		cameraMove: "handheld",
	},
	{
		id: "interest-shadow",
		narration:
			"대출 이자는 눈에 잘 안 보이지만, 매달 따라오는 그림자 고정비입니다.",
		visual:
			"same character walking with a heavy shadow shaped like a loan weight attached to the ankle, coins slowly leaking from wallet, Korean personal finance cartoon, dramatic but cute, clean vector style, no text, no letters",
		cameraMove: "crash-zoom-in",
	},
	{
		id: "money-flow",
		narration:
			"그래서 중요한 건 월급의 크기가 아니라, 월급이 어디로 흐르는지입니다.",
		visual:
			"same character watching a green paycheck river split into four jars for fixed costs saving investing spending, simple money flow metaphor, Korean economy cartoon, flat vector, warm colors, no text, no letters",
		cameraMove: "slow-zoom-in",
	},
	{
		id: "pay-yourself-first",
		narration:
			"먼저 고정비를 줄이고 저축을 떼어낸 다음, 남은 돈으로 소비해야 통장이 버팁니다.",
		visual:
			"same character smiling while placing coins into savings jar before opening a small spending wallet, paycheck mascot relaxed, clear payoff scene, optimistic economy cartoon, flat 2D vector, no text, no letters",
		cameraMove: "slider-right",
	},
];

function parseArgs(argv: string[]): Record<string, string> {
	const out: Record<string, string> = {};
	for (let i = 0; i < argv.length; i++) {
		if (!argv[i].startsWith("--")) continue;
		const key = argv[i].slice(2);
		const next = argv[i + 1];
		if (!next || next.startsWith("--")) out[key] = "true";
		else {
			out[key] = next;
			i++;
		}
	}
	return out;
}

function cartoonWorkflow(prompt: string, seed: number) {
	return textToImageWorkflow({
		positive: [
			"premium 2D animated economy cartoon keyframe",
			"consistent recurring Korean office worker character",
			"clean vector animation still",
			"bold outlines",
			"strong readable silhouette",
			"expressive face and action pose",
			"warm modern editorial palette",
			prompt,
		].join(", "),
		negative:
			"photorealistic, 3d render, stock photo, live action, text, letters, Korean text, subtitles, logo, watermark, signature, messy hands, deformed face, duplicate character, low quality, blurry",
		seed,
		filenamePrefix: "money_cartoon",
		width: 768,
		height: 1344,
		cfg: 6,
	});
}

async function ttsLocal(text: string, wavPath: string, mp3Path: string) {
	if (!existsSync(MELO_TTS)) {
		throw new Error(
			"MeloTTS 스크립트를 찾을 수 없습니다: " +
				MELO_TTS +
				" — MELO_TTS 환경변수로 경로를 지정하세요.",
		);
	}
	await exec(MELO_TTS, [
		text,
		wavPath,
		"kr",
		String(Math.min(2, Math.max(0.5, Number(process.env.TTS_SPEED) || 1.08))),
	]);
	await exec("ffmpeg", [
		"-y",
		"-i",
		wavPath,
		"-c:a",
		"libmp3lame",
		"-q:a",
		"2",
		mp3Path,
	]);
}

function writeSrt(
	scenes: { narration: string; durationSec: number }[],
	outPath: string,
) {
	const stamp = (sec: number) => {
		const total = Math.max(0, Math.round(sec * 1000));
		const ms = total % 1000;
		const s = Math.floor(total / 1000) % 60;
		const m = Math.floor(total / 60000) % 60;
		const h = Math.floor(total / 3600000);
		return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
	};
	let cursor = 0;
	const blocks: string[] = [];
	for (let i = 0; i < scenes.length; i++) {
		const start = cursor;
		cursor += scenes[i].durationSec;
		blocks.push(
			`${i + 1}\n${stamp(start)} --> ${stamp(cursor)}\n${scenes[i].narration}\n`,
		);
	}
	writeFileSync(outPath, blocks.join("\n"));
}

async function main() {
	const args = parseArgs(process.argv.slice(2));
	const outDir = args.out ?? DEFAULT_OUT;
	const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 12);
	const workDir = join(outDir, `payday-${stamp}`);
	mkdirSync(workDir, { recursive: true });

	const made: {
		imageUrl: string;
		audioUrl: string;
		narration: string;
		durationSec: number;
		cameraMove: ReturnType<typeof remotionMotionFor>;
		videoUrl?: string;
	}[] = [];

	for (let i = 0; i < SCENES.length; i++) {
		const scene = SCENES[i];
		const img = join(workDir, `${scene.id}.png`);
		const wav = join(workDir, `${scene.id}.wav`);
		const mp3 = join(workDir, `${scene.id}.mp3`);

		if (!existsSync(img) || args.force === "true") {
			process.stdout.write(
				`\n[${i + 1}/${SCENES.length}] ComfyUI keypose: ${scene.id}\n`,
			);
			await runComfyChecked(
				(seed) => cartoonWorkflow(scene.visual, seed),
				4242 + i * 101,
				img,
			);
		}

		if (!existsSync(mp3) || args.force === "true") {
			process.stdout.write(
				`[${i + 1}/${SCENES.length}] Local TTS: ${scene.id}\n`,
			);
			await ttsLocal(scene.narration, wav, mp3);
		}

		made.push({
			imageUrl: img,
			audioUrl: mp3,
			narration: scene.narration,
			durationSec: await dur(mp3),
			cameraMove: remotionMotionFor(scene.cameraMove),
		});
	}

	const ltxClip = join(workDir, "payday-hook-ltx.mp4");
	if (existsSync(ltxClip)) {
		made[0].videoUrl = ltxClip;
	}

	const outPath = join(workDir, "payday-money-cartoon-short.mp4");
	process.stdout.write("\nRemotion Shorts render...\n");
	await renderVlogRemotion({
		scenes: made,
		outPath,
		projectRoot: PROJECT_ROOT,
		compositionId: "YouTubeShorts",
		runId: `money-cartoon-${stamp}`,
		onProgress: (pct) => process.stdout.write(`\rrender ${pct}%`),
	});
	process.stdout.write("\n");

	writeFileSync(
		join(workDir, "storyboard.json"),
		JSON.stringify(SCENES, null, 2),
	);
	writeSrt(
		made.map((m) => ({
			narration: m.narration,
			durationSec: m.durationSec,
		})),
		join(workDir, "payday-money-cartoon-short.srt"),
	);

	writeFileSync(
		join(workDir, "manifest.json"),
		JSON.stringify(
			{
				title: "월급은 왜 사라질까?",
				output: outPath,
				stack: [
					"ComfyUI text-to-image keyposes",
					"local MeloTTS",
					"boltYT Remotion YouTubeShorts composition",
				],
				scenes: made,
			},
			null,
			2,
		),
	);

	process.stdout.write(`${outPath}\n`);
}

main().catch((error) => {
	process.stderr.write(
		`ERROR: ${error instanceof Error ? error.stack : error}\n`,
	);
	process.exit(1);
});
